using System.Linq;
using System.Numerics;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

/// <summary>
/// UI class to handle the selection of a player's job priorities.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class JobPriorityEditor : BoxContainer
{
    private const string CampaignJobId = "Assistant"; // SS14 DND: displayed as Contractor via localization.

    private readonly IClientPreferencesManager _preferencesManager;
    private readonly IPrototypeManager _prototypeManager;
    private readonly JobRequirementsManager _requirements;
    private bool _isDirty;

    /// <summary>
    /// A dictionary to map Department names / Categories to a box that holds individual job priority selector controls
    /// </summary>
    private readonly Dictionary<string, BoxContainer> _jobCategories = new();

    /// <summary>
    /// A list holding each RequirementsSelector and the name of the job it is setting the priority for.
    /// </summary>
    private readonly List<(ProtoId<JobPrototype>, RequirementsSelector)> _jobPriorities = new();

    /// <summary>
    /// The currently edited job priorities dictionary that matches the format of PlayerPreferences job priorities.
    /// </summary>
    public Dictionary<ProtoId<JobPrototype>, JobPriority> SelectedJobPriorities { get; private set; } = new();

    /// <summary>
    /// Event that is invoked when the player clicks "Save"
    /// </summary>
    public event Action<Dictionary<ProtoId<JobPrototype>, JobPriority>>? Save;

    /// <summary>
    /// Create a new job priority editor
    /// </summary>
    public JobPriorityEditor(
        IClientPreferencesManager preferencesManager,
        IPrototypeManager prototypeManager,
        JobRequirementsManager requirements
        )
    {
        _prototypeManager = prototypeManager;
        _requirements = requirements;
        _preferencesManager = preferencesManager;
        RobustXamlLoader.Load(this);

        ResetButton.OnPressed += args =>
        {
            LoadJobPriorities();
            CheckDirty();
        };

        SaveButton.OnPressed += args =>
        {
            Save?.Invoke(SelectedJobPriorities);
            UpdateJobPriorities();
            CheckDirty();
        };

        LoadJobPriorities();
        RefreshJobs();
    }

    public void LoadJobPriorities()
    {
        SelectedJobPriorities = _preferencesManager.Preferences?.JobPriorities.ShallowClone()
            ?? new Dictionary<ProtoId<JobPrototype>, JobPriority>();

        SelectedJobPriorities = SelectedJobPriorities
            .Where(kv => kv.Key == CampaignJobId)
            .ToDictionary(kv => kv.Key, kv => kv.Value);

        UpdateJobPriorities();
        CheckDirty();
    }

    public bool IsDirty()
    {
        return _isDirty;
    }

    private void SetDirty(bool dirty)
    {
        _isDirty = dirty;
        SaveButton.Disabled = !dirty;
        ResetButton.Disabled = !dirty;
    }

    /// <summary>
    /// Refreshes all job selectors.
    /// </summary>
    public void RefreshJobs()
    {
        JobList.DisposeAllChildren();
        _jobCategories.Clear();
        _jobPriorities.Clear();
        var firstCategory = true;

        // SS14 DND: keep the lobby focused on the single neutral campaign role.
        SelectedJobPriorities = SelectedJobPriorities
            .Where(kv => kv.Key == CampaignJobId)
            .ToDictionary(kv => kv.Key, kv => kv.Value);

        // Get all displayed departments
        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(dep => !dep.EditorHidden)
            .ToList();

        departments.Sort(DepartmentUIComparer.Instance);

        var selectorPriorities = new[]
        {
            ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
            ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
            ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
            ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
        };

        foreach (var department in departments)
        {
            var departmentName = Loc.GetString(department.Name);

            // If a department category hasn't yet been created in _jobCategories,
            // start a new one.
            if (!_jobCategories.TryGetValue(department.ID, out var category))
            {
                category = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    Name = department.ID,
                };

                if (firstCategory)
                {
                    firstCategory = false;
                }
                else
                {
                    category.AddChild(new Control
                    {
                        MinSize = new Vector2(0, 23),
                    });
                }

                category.AddChild(new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat {BackgroundColor = Color.FromHex("#464966")},
                    Children =
                    {
                        new Label
                        {
                            Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                ("departmentName", departmentName)),
                            Margin = new Thickness(5f, 0, 0, 0)
                        }
                    }
                });

                _jobCategories[department.ID] = category;
                JobList.AddChild(category);
            }

            var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                .Where(job => job.SetPreference && job.ID == CampaignJobId)
                .ToList();

            jobs.Sort(JobUIComparer.Instance);

            foreach (var job in jobs)
            {
                var jobContainer = new BoxContainer()
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector()
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };

                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center
                };
                var jobIcon = _prototypeManager.Index(job.Icon);
                icon.Texture = jobIcon.Icon.Frame0();
                var description = job.LocalizedDescription != null // Starlight BEGIN
                    ? FormattedMessage.FromUnformatted(job.LocalizedDescription)
                    : FormattedMessage.Empty;
                selector.Setup(selectorPriorities, job.LocalizedName, 200, description, icon, job.Guides); // Starlight END

                // This shouldn't depend on any character specific properties, so pass null
                if (!_requirements.IsAllowed(job, null, out var reason))
                {
                    selector.LockRequirements(reason);
                    SelectedJobPriorities[job.ID] = JobPriority.Never;
                    CheckDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += selectedPrio =>
                {
                    var selectedJobPrio = (JobPriority) selectedPrio;

                    SelectedJobPriorities[job.ID] = selectedJobPrio;

                    foreach (var (jobId, other) in _jobPriorities)
                    {
                        // Sync other selectors with the same job in case of multiple department jobs
                        if (jobId == job.ID)
                        {
                            other.Select(selectedPrio);
                            continue;
                        }

                        if (selectedJobPrio == JobPriority.High && (JobPriority) other.Selected == JobPriority.High)
                        {
                            // Lower any other high priorities to medium.
                            other.Select((int)JobPriority.Medium);
                            SelectedJobPriorities[jobId] = JobPriority.Medium;
                        }
                    }

                    UpdateJobPriorities();
                    CheckDirty();
                };

                _jobPriorities.Add((job.ID, selector));
                jobContainer.AddChild(selector);
                category.AddChild(jobContainer);
            }

            if (!category.Children.Any(child => child is BoxContainer))
            {
                JobList.RemoveChild(category);
                _jobCategories.Remove(department.ID);
            }
        }

        UpdateJobPriorities();
        CheckDirty();
    }

    /// <summary>
    /// Updates selected job priorities to the priority selectors.
    /// </summary>
    private void UpdateJobPriorities()
    {
        foreach (var (jobId, prioritySelector) in _jobPriorities)
        {
            prioritySelector.Select((int) SelectedJobPriorities.GetValueOrDefault(jobId, JobPriority.Never));
        }
    }

    /// <summary>
    /// Check if the selected priorities are different from the saved ones
    /// </summary>
    private void CheckDirty()
    {
        // If it equals default then reset the button.
        var savedJobPriorities = _preferencesManager.Preferences?.JobPriorities ?? new Dictionary<ProtoId<JobPrototype>, JobPriority>();
        savedJobPriorities = savedJobPriorities
            .Where(kv => kv.Key == CampaignJobId)
            .ToDictionary(kv => kv.Key, kv => kv.Value);

        if (!SelectedJobPriorities.Keys.ToHashSet().SetEquals(savedJobPriorities.Keys.ToHashSet()))
        {
            SetDirty(true);
            return;
        }

        foreach (var (job, prio) in SelectedJobPriorities)
        {
            if (prio != savedJobPriorities.GetValueOrDefault(job))
            {
                SetDirty(true);
                return;
            }
        }

        SetDirty(false);
    }
}
